# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SCM_CREDENTIALS }}
      - name: Setup Dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
      - name: 'Run dotnet build'
        shell: bash
        run: |
          # If your function app project is not located in your repository's root
          # Please consider using pushd to change your path
          pushd .
          dotnet build --configuration Release --output ./output
          popd
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.1.4
        with:
          # Name of the Azure Function App
          app-name: githubactionsfuncdemo         
          
